SCRIPT_DIR=`dirname $0`
TEMPLATE_DIR=$1

echo mkdir $SCRIPT_DIR/src
mkdir -p $SCRIPT_DIR/src

cp $TEMPLATE_DIR/LICENSE $SCRIPT_DIR/LICENSE
cp $TEMPLATE_DIR/README.md $SCRIPT_DIR/README.md
cp $TEMPLATE_DIR/RELEASE.md $SCRIPT_DIR/RELEASE.md

cp $TEMPLATE_DIR/src/package.json $SCRIPT_DIR/src/package.json

